# Generated by Django 3.2.20 on 2024-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuggestionId', models.IntegerField()),
                ('Title', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=400)),
                ('Vote', models.IntegerField(default=0)),
            ],
        ),
    ]
