# Generated by Django 3.2.20 on 2024-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestionsdata',
            old_name='Vote',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='suggestionsdata',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='suggestionsdata',
            name='SuggestionId',
        ),
        migrations.RemoveField(
            model_name='suggestionsdata',
            name='Title',
        ),
        migrations.AddField(
            model_name='suggestionsdata',
            name='description',
            field=models.TextField(default=' ', max_length=400),
        ),
        migrations.AddField(
            model_name='suggestionsdata',
            name='title',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
